[package]
name = "overlay"
version = "0.0.0"
description = "A Tauri App"
authors = ["Orion Reed"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-set-ignore-cursor-events", "global-shortcut-all", "macos-private-api", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
active-win-pos-rs = "0.9"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.23"
core-foundation = "0.9"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
